// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	N1                   float32  `protobuf:"fixed32,1,opt,name=n1,proto3" json:"n1,omitempty"`
	N2                   float32  `protobuf:"fixed32,2,opt,name=n2,proto3" json:"n2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetN1() float32 {
	if m != nil {
		return m.N1
	}
	return 0
}

func (m *Request) GetN2() float32 {
	if m != nil {
		return m.N2
	}
	return 0
}

type AddResponse struct {
	N1                   float32  `protobuf:"fixed32,1,opt,name=n1,proto3" json:"n1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetN1() float32 {
	if m != nil {
		return m.N1
	}
	return 0
}

type SubstractResponse struct {
	N1                   float32  `protobuf:"fixed32,1,opt,name=n1,proto3" json:"n1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubstractResponse) Reset()         { *m = SubstractResponse{} }
func (m *SubstractResponse) String() string { return proto.CompactTextString(m) }
func (*SubstractResponse) ProtoMessage()    {}
func (*SubstractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *SubstractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubstractResponse.Unmarshal(m, b)
}
func (m *SubstractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubstractResponse.Marshal(b, m, deterministic)
}
func (m *SubstractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubstractResponse.Merge(m, src)
}
func (m *SubstractResponse) XXX_Size() int {
	return xxx_messageInfo_SubstractResponse.Size(m)
}
func (m *SubstractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubstractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubstractResponse proto.InternalMessageInfo

func (m *SubstractResponse) GetN1() float32 {
	if m != nil {
		return m.N1
	}
	return 0
}

type MultiplyResponse struct {
	N1                   float32  `protobuf:"fixed32,1,opt,name=n1,proto3" json:"n1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplyResponse) Reset()         { *m = MultiplyResponse{} }
func (m *MultiplyResponse) String() string { return proto.CompactTextString(m) }
func (*MultiplyResponse) ProtoMessage()    {}
func (*MultiplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *MultiplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplyResponse.Unmarshal(m, b)
}
func (m *MultiplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplyResponse.Marshal(b, m, deterministic)
}
func (m *MultiplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplyResponse.Merge(m, src)
}
func (m *MultiplyResponse) XXX_Size() int {
	return xxx_messageInfo_MultiplyResponse.Size(m)
}
func (m *MultiplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplyResponse proto.InternalMessageInfo

func (m *MultiplyResponse) GetN1() float32 {
	if m != nil {
		return m.N1
	}
	return 0
}

type DivideResponse struct {
	N1                   float32  `protobuf:"fixed32,1,opt,name=n1,proto3" json:"n1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DivideResponse) Reset()         { *m = DivideResponse{} }
func (m *DivideResponse) String() string { return proto.CompactTextString(m) }
func (*DivideResponse) ProtoMessage()    {}
func (*DivideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{4}
}

func (m *DivideResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivideResponse.Unmarshal(m, b)
}
func (m *DivideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivideResponse.Marshal(b, m, deterministic)
}
func (m *DivideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivideResponse.Merge(m, src)
}
func (m *DivideResponse) XXX_Size() int {
	return xxx_messageInfo_DivideResponse.Size(m)
}
func (m *DivideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DivideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DivideResponse proto.InternalMessageInfo

func (m *DivideResponse) GetN1() float32 {
	if m != nil {
		return m.N1
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "calc.Request")
	proto.RegisterType((*AddResponse)(nil), "calc.AddResponse")
	proto.RegisterType((*SubstractResponse)(nil), "calc.SubstractResponse")
	proto.RegisterType((*MultiplyResponse)(nil), "calc.MultiplyResponse")
	proto.RegisterType((*DivideResponse)(nil), "calc.DivideResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x47, 0x30, 0x0b, 0x92, 0x90, 0x38, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0x11, 0x25, 0x4d, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x3e, 0x2e, 0xa6, 0x3c, 0x43, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xa6, 0x20, 0xa6,
	0x3c, 0x43, 0x30, 0xdf, 0x48, 0x82, 0x09, 0xca, 0x37, 0x52, 0x92, 0xe5, 0xe2, 0x76, 0x4c, 0x49,
	0x09, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x45, 0x57, 0xae, 0xa4, 0xcc, 0x25, 0x18, 0x5c,
	0x9a, 0x54, 0x5c, 0x52, 0x94, 0x98, 0x5c, 0x82, 0x53, 0x91, 0x12, 0x97, 0x80, 0x6f, 0x69, 0x4e,
	0x49, 0x66, 0x41, 0x4e, 0x25, 0x4e, 0x35, 0x0a, 0x5c, 0x7c, 0x2e, 0x99, 0x65, 0x99, 0x29, 0xa9,
	0xb8, 0x54, 0x18, 0x5d, 0x66, 0xe4, 0xe2, 0x72, 0x86, 0xfb, 0x47, 0x48, 0x93, 0x8b, 0xd9, 0x31,
	0x25, 0x45, 0x88, 0x57, 0x0f, 0xe4, 0x23, 0x3d, 0xa8, 0x77, 0xa4, 0x04, 0x21, 0x5c, 0x24, 0x27,
	0x2b, 0x31, 0x08, 0x99, 0x70, 0x71, 0x04, 0x97, 0x26, 0x81, 0xdd, 0x88, 0xae, 0x5e, 0x1c, 0xc2,
	0xc5, 0xf0, 0x83, 0x12, 0x83, 0x90, 0x31, 0x17, 0x07, 0xcc, 0xd5, 0xe8, 0xba, 0xc4, 0x20, 0x5c,
	0x74, 0x4f, 0x29, 0x31, 0x08, 0xe9, 0x73, 0xb1, 0x41, 0xbc, 0x81, 0xae, 0x45, 0x04, 0xc2, 0x45,
	0xf5, 0xa3, 0x12, 0x83, 0x93, 0x64, 0x94, 0x38, 0x8e, 0xc8, 0x4b, 0x62, 0x03, 0x47, 0x99, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x22, 0x55, 0xc1, 0x04, 0xde, 0x01, 0x00, 0x00,
}
